/* tslint:disable */
export const DATA: any[] = [{
  ProductID: 1,
  ProductName: "Chai",
  SupplierID: 1,
  CategoryID: 1,
  QuantityPerUnit: "10 boxes x 20 bags",
  UnitPrice: 18.0000,
  UnitsInStock: 39,
  UnitsOnOrder: 0,
  ReorderLevel: 10,
  Discontinued: false,
  OrderDate: new Date("2012-02-12")
}, {
  ProductID: 2,
  ProductName: "Chang",
  SupplierID: 1,
  CategoryID: 1,
  QuantityPerUnit: "24 - 12 oz bottles",
  UnitPrice: 19.0000,
  UnitsInStock: 17,
  UnitsOnOrder: 40,
  ReorderLevel: 25,
  Discontinued: true,
  OrderDate: new Date("2003-03-17")
}, {
  ProductID: 3,
  ProductName: "Aniseed Syrup",
  SupplierID: 1,
  CategoryID: 2,
  QuantityPerUnit: "12 - 550 ml bottles",
  UnitPrice: 10.0000,
  UnitsInStock: 13,
  UnitsOnOrder: 70,
  ReorderLevel: 25,
  Discontinued: false,
  OrderDate: new Date("2006-03-17")
}, {
  ProductID: 4,
  ProductName: "Chef Antons Cajun Seasoning",
  SupplierID: 2,
  CategoryID: 2,
  QuantityPerUnit: "48 - 6 oz jars",
  UnitPrice: 22.0000,
  UnitsInStock: 53,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: false,
  OrderDate: new Date("2016-03-17")
}, {
  ProductID: 5,
  ProductName: "Chef Antons Gumbo Mix",
  SupplierID: 2,
  CategoryID: 2,
  QuantityPerUnit: "36 boxes",
  UnitPrice: 21.3500,
  UnitsInStock: 0,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: true,
  OrderDate: new Date("2011-11-11")
}, {
  ProductID: 6,
  ProductName: "Grandmas Boysenberry Spread",
  SupplierID: 3,
  CategoryID: 2,
  QuantityPerUnit: "12 - 8 oz jars",
  UnitPrice: 25.0000,
  UnitsInStock: 0,
  UnitsOnOrder: 0,
  ReorderLevel: 25,
  Discontinued: false,
  OrderDate: new Date("2017-12-17")
}, {
  ProductID: 7,
  ProductName: "Uncle Bobs Organic Dried Pears",
  SupplierID: 3,
  CategoryID: 7,
  QuantityPerUnit: "12 - 1 lb pkgs.",
  UnitPrice: 30.0000,
  UnitsInStock: 150,
  UnitsOnOrder: 0,
  ReorderLevel: 10,
  Discontinued: false,
  OrderDate: new Date("2016-07-17")
}, {
  ProductID: 8,
  ProductName: "Northwoods Cranberry Sauce",
  SupplierID: 3,
  CategoryID: 2,
  QuantityPerUnit: "12 - 12 oz jars",
  UnitPrice: 40.0000,
  UnitsInStock: 6,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: false,
  OrderDate: new Date("2018-01-17")
}, {
  ProductID: 9,
  ProductName: "Mishi Kobe Niku",
  SupplierID: 4,
  CategoryID: 6,
  QuantityPerUnit: "18 - 500 g pkgs.",
  UnitPrice: 97.0000,
  UnitsInStock: 29,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: true,
  OrderDate: new Date("2010-02-17")
}, {
  ProductID: 10,
  ProductName: "Ikura",
  SupplierID: 4,
  CategoryID: 8,
  QuantityPerUnit: "12 - 200 ml jars",
  UnitPrice: 31.0000,
  UnitsInStock: 31,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: false,
  OrderDate: new Date("2008-05-17")
}, {
  ProductID: 11,
  ProductName: "Queso Cabrales",
  SupplierID: 5,
  CategoryID: 4,
  QuantityPerUnit: "1 kg pkg.",
  UnitPrice: 21.0000,
  UnitsInStock: 22,
  UnitsOnOrder: 30,
  ReorderLevel: 30,
  Discontinued: false,
  OrderDate: new Date("2009-01-17")
}, {
  ProductID: 12,
  ProductName: "Queso Manchego La Pastora",
  SupplierID: 5,
  CategoryID: 4,
  QuantityPerUnit: "10 - 500 g pkgs.",
  UnitPrice: 38.0000,
  UnitsInStock: 86,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: false,
  OrderDate: new Date("2015-11-17")
}, {
  ProductID: 13,
  ProductName: "Konbu",
  SupplierID: 6,
  CategoryID: 8,
  QuantityPerUnit: "2 kg box",
  UnitPrice: 6.0000,
  UnitsInStock: 24,
  UnitsOnOrder: 0,
  ReorderLevel: 5,
  Discontinued: false,
  OrderDate: new Date("2015-03-17")
}, {
  ProductID: 14,
  ProductName: "Tofu",
  SupplierID: 6,
  CategoryID: 7,
  QuantityPerUnit: "40 - 100 g pkgs.",
  UnitPrice: 23.2500,
  UnitsInStock: 35,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: false,
  OrderDate: new Date("2017-06-17")
}, {
  ProductID: 15,
  ProductName: "Genen Shouyu",
  SupplierID: 6,
  CategoryID: 2,
  QuantityPerUnit: "24 - 250 ml bottles",
  UnitPrice: 15.5000,
  UnitsInStock: 39,
  UnitsOnOrder: 0,
  ReorderLevel: 5,
  Discontinued: false,
  OrderDate: new Date("2014-03-17")
}, {
  ProductID: 16,
  ProductName: "Pavlova",
  SupplierID: 7,
  CategoryID: 3,
  QuantityPerUnit: "32 - 500 g boxes",
  UnitPrice: 17.4500,
  UnitsInStock: 29,
  UnitsOnOrder: 0,
  ReorderLevel: 10,
  Discontinued: false,
  OrderDate: new Date("2018-03-28")
}, {
  ProductID: 17,
  ProductName: "Alice Mutton",
  SupplierID: 7,
  CategoryID: 6,
  QuantityPerUnit: "20 - 1 kg tins",
  UnitPrice: 39.0000,
  UnitsInStock: 0,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: true,
  OrderDate: new Date("2015-08-17")
}, {
  ProductID: 18,
  ProductName: "Carnarvon Tigers",
  SupplierID: 7,
  CategoryID: 8,
  QuantityPerUnit: "16 kg pkg.",
  UnitPrice: 62.5000,
  UnitsInStock: 42,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: false,
  OrderDate: new Date("2005-09-27")
}, {
  ProductID: 19,
  ProductName: "Teatime Chocolate Biscuits",
  SupplierID: 8,
  CategoryID: 3,
  QuantityPerUnit: "",
  UnitPrice: 9.2000,
  UnitsInStock: 25,
  UnitsOnOrder: 0,
  ReorderLevel: 5,
  Discontinued: false,
  OrderDate: new Date("2001-03-17")
}, {
  ProductID: 20,
  ProductName: "Sir Rodneys Marmalade",
  SupplierID: 8,
  CategoryID: 3,
  QuantityPerUnit: undefined,
  UnitPrice: 4.5,
  UnitsInStock: 40,
  UnitsOnOrder: 0,
  ReorderLevel: 0,
  Discontinued: false,
  OrderDate: new Date("2005-03-17")
}
];

export const PRODUCTS: any[] = [{
  product: "Apple Watch 5 Aluminum",
  sku: "APMWv72LLA",
  supplier:"Apple",
  weight:"36.5 g",
  pkgDims: "44 x 38 x 10.74 mm",
  physOnHand: 0,
  available: 0,
  commited: 0
}, {
  product: "Apple 10.2\" iPad (Late 2019, 128GB, Wi-Fi + 4G LTE, Space Gray)",
  sku: "APIPWC128G10",
  supplier:"Apple",
  weight:"1.94 lb",
  pkgDims: "10 x 7 x 2 in",
  physOnHand: 1200,
  available: 1200,
  commited: 0
}, {
  product: "Apple 16\" MacBook Pro (Mid 2020, Silver)",
  sku: "APZOY3MVVM76",
  supplier:"Apple",
  weight:"4.19 lb",
  pkgDims: "18 x 12 x 5 in",
  physOnHand: 99,
  available: 99,
  commited: 0
}, {
  product: "Canon EOS R5 (Body Only)",
  sku: "CAER5",
  supplier:"Canon",
  weight:"3.56 lb",
  pkgDims: "11.1 x 9 x 6\"",
  physOnHand: 127,
  available: 12,
  commited: 115
}, {
  product: "Canon EOS R6 (Body Only)",
  sku: "CAER6",
  supplier:"Canon",
  weight:"3.31 lb",
  pkgDims: "11 x 8.9 x 5.9\"",
  physOnHand: 250,
  available: 240,
  commited: 10
}, {
  product: "Canon Speedlite 600EX II-RT",
  sku: "CA600EX2",
  supplier:"Canon",
  weight:"1.93 lb",
  pkgDims: "6.7 x 5.95 x 4.45\"",
  physOnHand: 13,
  available: 12,
  commited: 1
}]
/* tslint:enable */
